#env_params:
task_name: 'ReorientUp'
task_description:
  'screw bottle cap for opening or closing'

env:
  numEnvs: 200
  envSpacing: 0.75
  episodeLength: 600
#  resetTime: 10
#  frame_skip: 4
  random_prior: True
  repose_z: True
  enableDebugVis: True
  aggregateMode: 1
  real_tip_tac: False


  vel_reward_scale: 1.0 # changed from 0 to 0.5,from 0.5 to 1
  dis_reward_scale: 0.25
  ignore_z_dist: True
  max_z_theta: 60    #45degree
  fingertip_tac: False


  #  full_obs: False
  asset:

    assetRoot: "./asset"
    assetFileNameRobot: "shadow_hand/mjcf/open_ai_assets/hand/shadow_hand_sensor.xml"
#    assetFileNameObj: "/shadow_hand/objects/cube_multicolor.urdf"
    assetFileNameObj: "/reorient_up/"

  env_dict:

#reorient up objects train/seen
        - ddg-ycb_065-c_cups
        - ddg-ycb_056_tennis_ball
        - ddg-ycb_012_strawberry
        - ddg-ycb_003_cracker_box
        - ddg-ycb_013_apple
        - ddg-ycb_077_rubiks_cube
        - ddg-ycb_070-a_colored_wood_blocks
        - ddg-ycb_010_potted_meat_can
        - ddg-ycb_014_lemon
        - ddg-gd_rubber_duck_poisson_001

#reorient up objects test/unseen
#          - ddg-ycb_072-d_toy_airplane
#          - ddg-ycb_061_foam_brick
#          - ddg-ycb_018_plum
#          - ddg-ycb_063-a_marbles
#          - ddg-ycb_073-f_lego_duplo



  # env param
  obs_type:
    "Base"
  obs_dim:
    prop: 48 #propriception
#    vis: 150528    #224*224*3
#    tac: 20

  action_dim: 20

  img_w: 224
  img_h: 224
  #act_dim: 21

  vision:
    camera:
      # relative to table center
      eye: [
                [ 0.3, 0.3, 0.4 ],  #ori1, ori2
      ]
      lookat: [

        [ 0.22, 0, 0.05 ], #ori2_look_shift_to_right



      ]

  random_load:
    sequential: True
    num_obj_per_env: 1  # maximum a * b * 4 + 1 # 257
    obj_width: 0.1
    a: 2 #4
    b: 2

  clip_observations: 5.0
  clip_actions: 1.0


  stiffnessScale: 1.0
  forceLimitScale: 1.0
  useRelativeControl: False
  dofSpeedScale: 20.0
  actionsMovingAverage: 1.0
  controlFrequencyInv: 1 # 60 Hz

  startPositionNoise: 0.01
  startRotationNoise: 0.0

  resetPositionNoise: 0.01
  resetRotationNoise: 0.0
  resetDofPosRandomInterval: 0.2
  resetDofVelRandomInterval: 0.0

  # Random forces applied to the object
  forceScale: 0.0
  forceProbRange: [0.001, 0.1]
  forceDecay: 0.99
  forceDecayInterval: 0.08

  distRewardScale: -10
  transition_scale: 0.05
  orientation_scale: 0.5
  rotRewardScale: 1.0
  rotEps: 0.1
  actionPenaltyScale: -0.0002
  reachGoalBonus: 250
  fallDistance: 0.24 # changed from 0.24 to 0.04
  fallPenalty: 0.0

  objectType: "block" # can be block, egg or pen
  observationType: "full_state" # can be "openai", "full_no_vel", "full", "full_state"
  asymmetric_observations: False
  successTolerance: 0.1
  printNumSuccesses: False
  maxConsecutiveSuccesses: 0




task:
  randomize: False
  randomization_params:
    frequency: 600   # Define how many simulation steps between generating new randomizations
    observations:
      range: [ 0, .002 ] # range for the white noise
      range_correlated: [ 0, .001 ] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"   # "constant" is to turn on noise after `schedule_steps` num steps
      schedule_steps: 40000
    actions:
      range: [ 0., .05 ]
      range_correlated: [ 0, .015 ] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
      schedule_steps: 40000
    sim_params:
      gravity:
        range: [ 0, 0.4 ]
        operation: "additive"
        distribution: "gaussian"
        schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
        schedule_steps: 40000
    actor_params:
      hand:
        color: True
        tendon_properties:
          damping:
            range: [ 0.3, 3.0 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          stiffness:
            range: [ 0.75, 1.5 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        dof_properties:
          damping:
            range: [ 0.3, 3.0 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          stiffness:
            range: [ 0.75, 1.5 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          lower:
            range: [ 0, 0.01 ]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          upper:
            range: [ 0, 0.01 ]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_body_properties:
          mass:
            range: [ 0.5, 1.5 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [ 0.7, 1.3 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
      object:
        scale:
          range: [ 0.95, 1.05 ]
          operation: "scaling"
          distribution: "uniform"
          schedule: "linear"  # "linear" will scale the current random sample by ``min(current num steps, schedule_steps) / schedule_steps`
          schedule_steps: 30000
        rigid_body_properties:
          mass:
            range: [ 0.5, 1.5 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by ``min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [ 0.7, 1.3 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000


sim:
  dt: 0.01667 # 1/60
  substeps: 2
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.002
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

video_path : '/videos'

